version: "3.0"
services:
  backend:
    build: ./backend
    ports:
      - 3000:443
    volumes:
      - ./backend/src:/var/www/html
    environment:
      IS_DEVELOP: "true"
      DB_PASSWORD: "development"
      
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: development
        MYSQL_PASSWORD: development
    ports:
        - 3306:3306
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d
        