version: "3.0"
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - 3000:80
    volumes:
      - ./backend/src:/var/www/html
    environment:
      IS_DEVELOP: "true"
      
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: development
        MYSQL_PASSWORD: development
    ports:
        - 3306:3306
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d
        